# To use:
#
#   $ mamba env create -f environment.yml
#   $ mamba activate pyseamsdev
#
name: pyseamsdev
channels:
  - conda-forge
dependencies:
  - python >=3.12
  - compilers
  - meson
  - ninja
  - cmake
  - pkg-config
  - eigen
  - libblas
  - liblapack
  - nanobind
  - numpy
  - pip
  - pytest
  - pre-commit
  - clang-format
  - ruff
