name: "Build pydseamslib and test"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml

      - name: Install and test
        shell: bash -el {0}
        run: |
          pip install -v '.[test,ase]'
          python -c 'import pydseamslib as ds; print(ds.__version__); print(ds.cyoda)'
          python -m pytest -vvv tests
