# Kanged from eOn : https://github.com/TheochemUI/eOn
name: Build documentation
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build_docs:
    name: Build documentation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Generate Docs
        run: |
          pip install sphinx shibuya myst-parser sphinx-copybutton \
            sphinx-design sphinxcontrib-bibtex sphinx-contributors
          sphinx-build -b html docs/source html
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'html'
  deploy:
    needs: build_docs
    runs-on: ubuntu-latest
    if: (github.event.pull_request.merged == true || github.event_name == 'push') && github.repository == 'd-SEAMS/PydSEAMSlib' && github.ref == 'refs/heads/main'
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
